### PR TITLE
Avatar for all user, user profile , grades assigned on profile

### PR DESCRIPTION
**Pull request by bit2gb**
Avatar for all user obtained by encodeng uuid in base 16, grades obtained on server or assigned by ranksystem, independent profile for all user and other

### CODE REVIEW

**Comment by Shad86** [comment]
you have to exclude the nav.php, we cant merge this pull with that "stats/nav.php" we wont remove our own copyright ;D

**Comment by bit2gb** [comment]
i saw in issue message, i replace your copyright, eventualy i put some information from me or about me. 
I dont understand what is the problem with nav.php?

**Comment by Shad86** [comment]
Its our Project, and let me say, the nav.php is usually a file that wont get touched/edited from users, because there are all relevant supporters and copyrights listed.

So let me say, you can expand things on nav.php but not removing it.

**Comment by bit2gb** [comment]
If you look now i change title , so now in nav.php exist only expanded/added rows

**Comment by Shad86** [comment]
You removed the languages dropdowns - I added them again - i think now should be all okay. 
On the end @Newcomer1989 will finally decide then if its worth enough :)

**Comment by bit2gb** [comment]
oooh sorry i forgot languages menu, for me is important only RO and EN. Also in your opinion is useful my ideas and work?

**Comment by bit2gb** [comment]
hey i make an average player /hour based on online players in last 7 days.
My question is where is the good location for place the result?

**Comment by Newcomer1989** [comment]
> Avatar for all user obtained by encodeng uuid in base 16, grades obtained on server or assigned by ranksystem, independent profile for all user and other

I am not sure, I am willing to open the my_stats.php for each one. I had this idea at the beginning we created the new stats/ page and at this point also the my_stats.php
We decided us to let this kind of information private, so only the user himself can see his own full stats. There are much information which could be used to control -> How long was a user online this week? How long of that he was active?

I think this a thing of privacy!

*Perhaps* I will open a voting for that topic with something like the following options:
a) Open my_stats.php for all - All user can see all stats of each one
b) Open my_stats.php only for admins - Only admins of the Ranksystem can see full stats of each one. Others can only see their own stats
c) Don't touch my_stats.php

What do you think about that privacy problem? Also other are welcome to share their opinion with us!

> Edit: Done, i place result on the bar of chart in page /stats/index.php

I am not be able to see that in your pull request.

**Comment by Shad86** [comment]
b

**Comment by Newcomer1989** [comment]
A bit time is gone.

I thought about it.. And I am still on the same opinion. It is a thing of privacy to do not share so much information with the public.

If you really want to see this feature, you should change it that every user has to allow (Opt-in) to share his information for the public. And only this one, which allowed it, will be showing..

**Pull request closed without merging**
