### PR TITLE
Completed Russian translation for 1.2.2

### PR DESCRIPTION
**Pull request by bykidi**
Translated (almost) everything, fixed typos, shorted some phrases like 'Client Database-ID: %id%' to 'DBID: %id%' and such.

### CODE REVIEW

**Comment by Newcomer1989** [comment]
Please do not put comments and/or questions inside the source code. It would be nice, if you ask this here as conversion to the commit.
I have now much work to clean your commit.

**Comment by bykidi** [comment]
there is only few of them

**Comment by Newcomer1989** [comment]
> $lang['msg0005']			= "cya"; //wth is that

cya = see you (like: bye)

> $lang['msg0006']			= "brb"; //and that

brb = be right back

**Comment by bykidi** [comment]
@Newcomer1989 i meant, where and why exactly these strings are used for?

**Comment by Newcomer1989** [comment]
That are messages, which you get from the Ranksystem bot as answer on your command.

**Comment by bykidi** [comment]
@Newcomer1989 oh, ok

**Comment by Newcomer1989** [comment]
Please give me a hint, if you are finished with your changes, before I adopt it in the dev version.

**Comment by bykidi** [comment]
I think it's done.

**Comment by Newcomer1989** [comment]
> $lang['nameitlikeyouwish']		= "Ничего не выбрано"; //Nothing selected. Currently missing in the ranksystem lang file. /webinterface/admin.php

This is not so easy to translate. The text comes from a Javascript file. To make it translatable I would have to embed it inside the website instead of a separated JS-file. Due this the performance of the whole webinterface would go down (no caching), so I decided to let it untranslated.

**Pull request merged**
