### PR TITLE
Update core_de.php

### PR DESCRIPTION
**Pull request by xopez**
$lang['clean0003'] was 2 times there with different meaning. Took the one which matches with core_en.php

### CODE REVIEW

**Comment by DoktorekOne** [comment]
https://ts-n.net/ranksystem.php

Polish language

core_pl.php

https://pastebin.com/Njhp2Qn1

and

nations_pl

https://pastebin.com/eFekkfv9

**Comment by xopez** [comment]
I made a new pull request for the new language which isn't there.
#445

**Comment by DoktorekOne** [comment]
ok

**Comment by Newcomer1989** [comment]
@xopez Thx for the hint. The double defined variable was cleaned with release 1.2.6

@DoktorekOne Thx for the polish translation.. I will be added with release 1.2.7

**Pull request closed without merging**
