### PR TITLE
Create robots.txt

### PR DESCRIPTION
**Pull request by xopez**
to disallow indexing
 #425

### CODE REVIEW

**Comment by Newcomer1989** [comment]
declined

This is the job of each web administrator. I think it shouldn't be done by an application.

When I am not wrong, the robots.txt should be lying inside the root folder of the webspace and in best case give information for all the different (sub)folders. Then every person should manage it for himself, what he wishes would be listed and what not.

**Comment by bykidi** [comment]
I can understand the indexing of main ranksystem pages, but search engine indexing an entire ranksystem including list_rankup.php which is looking badly

**Comment by bykidi** [comment]
I can disable the indexing of certain pages but it is will be overwritten by your next update - this is the problem

**Comment by Newcomer1989** [comment]
Do not change this inside of the Ranksystem folder!
You have to set the robots file inside your root directory of your webserver!

**Pull request closed without merging**
